### ISSUE TITLE
Add possibility to make GIFs

### ISSUE THREAD

**Issue by eirikgje** [Cosmoglobe/c3pp#1]
Some kind of functionality where you could give a deterministic filename-scheme and make GIFs out of them would be cool!

**Comment by trygvels** [comment]
Så en -outname liksom?

Trygve


On 21 Jan 2020, at 14:26, Eirik Gjerløw <notifications@github.com> wrote:

﻿

Some kind of functionality where you could give a deterministic filename-scheme and make GIFs out of them would be cool!

**Comment by eirikgje** [comment]
Mer sånn: "-gif_pattern inmap_{}_2048.fits -gif_range 1 10000 -gif_intervals 100 -gif_padding 6"
for da å lage gifs av alle kart mellom inmap_000001_2048.fits til inmap_010000_2048.fits, men bare hvert 100. kart.

**Comment by trygvels** [comment]
Done. ex: c3pp plot res_030_c0001_k00000*.fits -gif -auto -fwhm 120
Will add more functionality later.
