### ISSUE TITLE
Add option for WMAP colormap

### ISSUE THREAD

**Issue by dncnwtts** [Cosmoglobe/c3pp#16]
Just because sometimes it's nice to compare to older figures

![Screenshot from 2021-02-04 14-43-05](https://user-images.githubusercontent.com/6478137/106900964-70c75900-66f7-11eb-95a8-d6790731279d.png)

**Comment by dncnwtts** [comment]
@trygvels do your magic

[wmap.txt](https://github.com/Cosmoglobe/c3pp/files/5926296/wmap.txt)

**Comment by trygvels** [comment]
added `-cmap wmap`
