### ISSUE TITLE
make remove_dipole argument less opaque

### ISSUE THREAD

**Issue by dncnwtts** [Cosmoglobe/c3pp#9]
I need to type `-remove_dipole TEXT` and I don't know what the `TEXT` argument is supposed to be. I feel like this should be an optional argument

**Comment by trygvels** [comment]
Text argument is the mask to remove the dipole outide of

Trygve


On 24 Oct 2020, at 15:10, Duncan Watts <notifications@github.com> wrote:

﻿

I need to type -remove_dipole TEXT and I don't know what the TEXT argument is supposed to be. I feel like this should be an optional argument

**Comment by dncnwtts** [comment]
Would it make sense to have a default mask? I usually don't know which one is good.

**Comment by dncnwtts** [comment]
Tried to give this a go in [this pull request](https://github.com/trygvels/c3pp/pull/10). What do you think?
